version: '3'

services:
  database:
    container_name: MongoLito
    image: mongo:6.0.6
    volumes:
      - VolMongo:/data/db
    ports:
      - 27017:27017
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=Mongo_Ochue
      - MONGO_INITDB_ROOT_PASSWORD=user_password
    command: ['--auth']
  dbmanager:
    depends_on:
      - database
    container_name: mongoExpress
    image: mongo-express:1.0.0-alpha.4
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=Mongo_Ochue
      - ME_CONFIG_MONGODB_ADMINPASSWORD=user_password
      - ME_CONFIG_MONGODB_SERVER=MongoLito
    restart: always

volumes:
  VolMongo:
    external: false